apiVersion: apps/v1
kind: Deployment 
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2 
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: prajwal1027/database-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 

---

apiVersion: v1 
kind: Service 
metadata: 
  name: web-ssvc
spec:
  selector:
    app: web  
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
